/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as CombatTrackerRouteImport } from './routes/combat-tracker'
import { Route as IndexRouteImport } from './routes/index'

const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const CombatTrackerRoute = CombatTrackerRouteImport.update({
  id: '/combat-tracker',
  path: '/combat-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combat-tracker': typeof CombatTrackerRoute
  '/converter': typeof ConverterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combat-tracker': typeof CombatTrackerRoute
  '/converter': typeof ConverterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combat-tracker': typeof CombatTrackerRoute
  '/converter': typeof ConverterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combat-tracker' | '/converter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combat-tracker' | '/converter'
  id: '__root__' | '/' | '/combat-tracker' | '/converter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombatTrackerRoute: typeof CombatTrackerRoute
  ConverterRoute: typeof ConverterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combat-tracker': {
      id: '/combat-tracker'
      path: '/combat-tracker'
      fullPath: '/combat-tracker'
      preLoaderRoute: typeof CombatTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombatTrackerRoute: CombatTrackerRoute,
  ConverterRoute: ConverterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
